In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import os
dirpath = os.getcwd()
print("current directory is : " + dirpath)
foldername = os.path.basename(dirpath)
print("Directory name is : " + foldername)
# Aquí debe indicar la ubicación de sus archivos
os.chdir("/content/drive/MyDrive/Estructura_del_Computador/Procesamiento_Imagen")
dirpath = os.getcwd()
print("current directory is : " + dirpath)
foldername = os.path.basename(dirpath)
print("Directory name is : " + foldername)

current directory is : /content/drive/My Drive/Estructura_del_Computador/Procesamiento_Imagen
Directory name is : Procesamiento_Imagen
current directory is : /content/drive/MyDrive/Estructura_del_Computador/Procesamiento_Imagen
Directory name is : Procesamiento_Imagen


In [ ]:
import numpy as np
import imageio
import matplotlib.pyplot as plt
from PIL import Image, ImageOps

In [ ]:
imagen = imageio.imread(os.path.join(dirpath,'Eduardo_Zurek_ejemplo.jpg'))
im0 = Image.fromarray(imagen)
im0 = ImageOps.fit(im0, (1024,768))
imagen = np.asarray(im0,'uint8')
im1 = Image.fromarray(imagen)
im1 = im1.save("EZ_640_480.bmp")

/tmp/ipython-input-1183685347.py:1: DeprecationWarning: Starting with ImageIO v3 the behavior of this function will switch to that of iio.v3.imread. To keep the current behavior (and make this warning disappear) use `import imageio.v2 as imageio` or call `imageio.v2.imread` directly.
  imagen = imageio.imread(os.path.join(dirpath,'Eduardo_Zurek_ejemplo.jpg'))


In [ ]:
print(imagen.shape)
red = imagen[:,:,0].flatten()
print(red.shape)
green = imagen[:,:,1].flatten()
print(green.shape)
blue = imagen[:,:,2].flatten()
print(blue.shape[0])

(480, 640, 3)
(307200,)
(307200,)
307200


In [ ]:
atest = np.array(((1,2,3,4,5),(6,7,8,9,10),(11,12,13,14,15),(16,17,18,19,20)))
print(atest)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [ ]:
anew = atest.flatten()
print(anew)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [ ]:
azul = np.uint8(blue)
verde = np.uint8(green)
rojo = np.uint8(red)
representacion = np.uint16(rojo+verde+azul)

In [ ]:
print(bin(azul[0]))
print(len(azul))
for i in range(20):
  print([format(rojo[i],'02x')+format(verde[i],'02x')+format(azul[i],'02x'),hex(rojo[i]),bin(rojo[i]),hex(verde[i]),bin(verde[i]),hex(azul[i]),bin(azul[i])])

0b110110
307200
['1e7936', '0x1e', '0b11110', '0x79', '0b1111001', '0x36', '0b110110']
['1d7833', '0x1d', '0b11101', '0x78', '0b1111000', '0x33', '0b110011']
['338e44', '0x33', '0b110011', '0x8e', '0b10001110', '0x44', '0b1000100']
['47a356', '0x47', '0b1000111', '0xa3', '0b10100011', '0x56', '0b1010110']
['2c883e', '0x2c', '0b101100', '0x88', '0b10001000', '0x3e', '0b111110']
['1d7832', '0x1d', '0b11101', '0x78', '0b1111000', '0x32', '0b110010']
['1f7934', '0x1f', '0b11111', '0x79', '0b1111001', '0x34', '0b110100']
['1f7935', '0x1f', '0b11111', '0x79', '0b1111001', '0x35', '0b110101']
['217b36', '0x21', '0b100001', '0x7b', '0b1111011', '0x36', '0b110110']
['247e37', '0x24', '0b100100', '0x7e', '0b1111110', '0x37', '0b110111']
['28823a', '0x28', '0b101000', '0x82', '0b10000010', '0x3a', '0b111010']
['2d863d', '0x2d', '0b101101', '0x86', '0b10000110', '0x3d', '0b111101']
['2c863a', '0x2c', '0b101100', '0x86', '0b10000110', '0x3a', '0b111010']
['2b8737', '0x2b', '0b101011', '0x87', '0b10

In [ ]:
# prompt: escribe un programa en python que genere un archivo memory initialization file (.mif) de datos aleatorios con los siguientes parámetros:
# DEPTH = 165310 , el tamaño máximo del archivo para este ejemplo es 164310 = 542x305
# WIDTH = 24  , el tamaño máximo de la memoria es 524288
# ADDRESS_RADIX = HEX
# DATA_RADIX = HEX

import random

def generate_mif_file(depth, width, filename="memory_init_1024_768_gray_4bit.mif"):
    """Generates a .mif file with random data."""

    with open(filename, "w") as f:
        f.write("DEPTH = " + str(depth) + ";\n")
        f.write("WIDTH = " + str(width) + ";\n")
        f.write("ADDRESS_RADIX = HEX;\n")
        f.write("DATA_RADIX = HEX;\n")
        f.write("CONTENT BEGIN\n")

        for i in range(depth):
            gray = ((0.299*rojo[i]+0.587*verde[i]+0.114*azul[i])/16.0).astype(np.uint8)
            hex_data = format(gray,'01x')
            f.write(f"{i:05X} : {hex_data};\n")

        # for i in range(depth):
        #     bin_data = format(rojo[0],'08b')[:4]+format(verde[0],'08b')[:4]+format(azul[0],'08b')[:3]
        #     #hex_data = format(rojo[i],'02x')+format(verde[i],'02x')+format(azul[i],'02x') #hex(random.randint(0, (1 << width) - 1))[2:].zfill(int(width / 4))
        #     f.write(f"{i:05X} : {bin_data};\n")

        f.write("END;\n")

# Example usage:
depth = blue.shape[0]
generate_mif_file(depth, 4)  # Creates memory_init.mif with default name



In [ ]:
print(format(rojo[0],'08b'))
print(format(rojo[0],'08b')[:4])
print(format(verde[0],'08b'))
print(format(verde[0],'08b')[:4])
print(format(azul[0],'08b'))
print(format(azul[0],'08b')[:3])
bin_data = format(rojo[0],'08b')[:4]+format(verde[0],'08b')[:4]+format(azul[0],'08b')[:3]
print(bin_data)

00011110
0001
01111001
0111
00110110
001
00010111001
